### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Syafiq1331** [zuramai/portofolio-v2#121]
Penulisan deskripsi pada project portfolio-v2 sepertinya typo, karena di tulisan itu nutjs. Mungkin nuxt.js seharusnya :)

Terima kasih:)
![Screenshot_2022-05-07-20-17-24-42](https://user-images.githubusercontent.com/71716582/167256081-8618053d-a24c-48d6-a5ad-9d4e47d1c3fb.jpg)

**Comment by zuramai** [comment]
Hahaha iya terima kasih udah notice, sebenernya project ini juga udah unmaintained sih
